[tachometer]
min = 0
max = 8000
redline = 6700
mid_sections = 20
denomination = 1000
major_step = 1000

[speedometer]
min = 0
max = 180
mid_sections = 20
major_step = 20

[coolant_temp]
min = 0
max = 300
visual_num_gap=75
mid_sections = 8
redline = 225
blueline = 75

[oil_temp]
min = 0
max = 250
mid_sections = 3
redline = 220
blueline = 80

