[tachometer]
 min_unit = 0
 max_unit = 8000
 redline = 6700
 mid_sections = 4
 denomination = 1000
 visual_num_gap = 1000

[speedometer]
 min_unit = 0
 max_unit = 180
 mid_sections = 2
 visual_num_gap = 20

[coolant_temp]
 min_unit = 0
 max_unit = 400
 visual_num_gap = 50
 mid_sections = 2
 redline = 350
 blueline = 80

[fuel_level]
 min_unit = 0
 max_unit = 100
 visual_num_gap = 20
 redline = 101
 mid_sections = 3

[oil_temp]
 min_unit = 0
 max_unit = 250
 mid_sections = 3
 redline = 220
 blueline = 80
